trigger:
  - main

jobs:
  - job: Build1
    displayName: 'Grafana-Prometheus Setup'
    pool:
      name: ansible_agent
    steps:
    - script: ansible-playbook /home/ansible/Grafana-Prometheus/grafana-prometheus.yml
      displayName: 'Run Ansible Playbook for Grafana-Prometheus Setup'

  - job: Build2
    displayName: 'Docker Image Build'
    dependsOn: Build1
    pool:
      name: docker_agent
    steps:
    - script: |
        # Build Docker images
        # docker-compose -f /home/devops/docker-compose.yml up --no-start
        
        # Save new Docker images as tar files
        docker save -o prometheus.tar prom/prometheus:latest
        docker save -o grafana.tar grafana/grafana:latest
        
        # Move tar files to a separate directory
        mkdir -p $(Pipeline.Workspace)/docker-images
        mv prometheus.tar $(Pipeline.Workspace)/docker-images/
        mv grafana.tar $(Pipeline.Workspace)/docker-images/
      displayName: 'Build Docker Images and Save as Tar Files'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: $(Pipeline.Workspace)/docker-images
        artifactName: docker-images
        publishLocation: 'Container'
      displayName: 'Publish Docker Images as Artifacts'
